language: node_js
node_js:
  - "7"

git:
  depth: 3

cache:
  yarn: true

install: 
  - yarn

script: 
 - yarn run test
 
before_deploy: "echo 'ready?'"

deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    node: "7"
env:
  global:
    - NODE_ENV=production
    #GITHUB_TOKEN
    - secure: enCgJW0s2x5lYzR6qnH2wPcb8flI9hrbuVQnfQCee0VG3z8HmHRzyGRIlDep0K1u+TvWVD0ueQ29XMcQScjnWMe8wgMPGlWztHS1dcg/MV9QDg38fLshTT2IdZDcijo1N4lh/SZF+6c+LUjeyj+IzZAW/41tgOkdUJtuuJQwNJ4Fe3deP3sVucsjgAvGOlkmSJ7U5Q3mpK4YD59M2daJW5WUMb3YBazQXAIcodN/bWl58GezuR3tMeg12rVDQvvxboCCSB+CwH6YOvdbGJStIrQnnmRlaG+Oj0pq38whNtkIZH7SMJlatF2m8KGmT16EwYknpsUp1myRC62919PXgG6W1bmtRVN/Y8HQJ95aGFYcOJBa87kQTX9oXKUk33eI7uE2ALnbNFLyc44Qu1Qgfom5BbMtqgCYL5qA/KoQMKc3b2r+PbGr0LWamY6I4uUkZRxsO6HBIUhE+2gPlE6I+dAl2p/5lMFrrxamFVNkRRB18buty013/KsCJffwHBSFQ45LSdSscLa+E/7BqPn7aohYRuKTbWUdauId2F8iI63JiUciXZaNsOnG7fEv9OSyrqfechPFGYOzq9+IgrDm9QdG/AjNkYczr+lSqTe8lY3/fs8ZcBUi9KK8WjUD7znRcPaxqBaJlHo+2EYUP/PXkWQxA1sT85uGJauMO+WPdtY=
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/ITILostTime/yarnAndCI.git
